output_dir_folder: ./res_out
input_dir_folder: /home/casado/DsensDp/data/out/
additional_method_name: -Plus
load_memory: True
data_name: cropharvest_binary
task_type: classification
save_weights: True
save_test_set: True
weights_dir: ./res_out/weights
testset_dir: ./res_out/test_sets

training:
  max_epochs: 100
  batch_size: 128
  emb_dim: 128
  # early_stop_args:
  #   min_delta: 0.01
  #   mode: min
  #   patience: 5
  #   verbose: True
  early_stop_args:
    min_delta: 0.0
    mode: min
    patience: 50
  parallel_processes: 1
  missing_as_aug: True
  missing_method:
    random_perc: 0.5
    name: ignore
  additional_args:
    optimizer: adam
    lr: 0.001
  weights_loss_variations:
    main: 1
    full: 1
    individual_sd: 1
    individual: 1
    cross_temp: 0.5

experiment:
  runs_seed: [5]
  kfolds: 5
  preprocess:
    fillnan: False
    flatten: False
    form: zscore
    view_names: ["S2_S2VI", "S1", "weather", "DEM"]
  args_forward:
    list_testing_views: [
      [ ["S2_S2VI", "S1", "weather"], [1.00] ],
      [ ["S2_S2VI", "S1", "DEM"],     [1.00] ],
      [ ["S2_S2VI", "weather", "DEM"],[1.00] ],
      [ ["S1", "weather", "DEM"],     [1.00] ],
      [ ["S2_S2VI"], [1.00] ],
      [ ["S1"],      [1.00] ],
      [ ["weather"], [1.00] ],
      [ ["DEM"],     [1.00] ],
    ]
  batch_size: 64

architecture:
  encoders:
    S1:
      model_type: tempcnn
      dropout: 0.2
      kernel_size: 5
      layer_size: 128
      n_layers: 2
      seq_len: 12
      use_norm: False
    S2_S2VI:
      model_type: tempcnn
      dropout: 0.2
      kernel_size: 5
      layer_size: 128
      n_layers: 2
      seq_len: 12
      use_norm: False
    weather:
      model_type: tempcnn
      dropout: 0.2
      kernel_size: 5
      layer_size: 128
      n_layers: 2
      seq_len: 12
      use_norm: False
    DEM:
      model_type: mlp
      n_layers: 1
      layer_size: 128
      dropout: 0.2
      batchnorm: False
      use_norm: False
  predictive_model:
    n_layers: 1
    layer_size: 128
    dropout: 0.2
    batchnorm: True
    use_norm_last: True

method:
  feature: False
  znorm_logits: True
  agg_args:
    mode: avg